apiVersion: v1
kind: Secret
metadata:
  name: minio
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucket: tempo
  endpoint: http://minio.minio.svc:9000
type: Opaque
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
spec:
  storage:
    secret:
      name: minio
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 4Gi
        cpu: 4000m
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          route:
            termination: edge
          type: route
